receivers:
  filelog:
    include: [ /var/log/data/*.log ]

processors:
  batch:

exporters:
  otlp/notls:
    endpoint: logtemplate:9999
    tls:
      insecure: true
      insecure_skip_verify: true

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [health_check,pprof,zpages]
  pipelines:
    logs:
      receivers: [filelog]
      processors: [batch]
      exporters: [otlp/notls]