services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./otel-collector/otel-collector-config.yml:/etc/otel/config.yaml
      - ./otel-collector/data:/var/log/data
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "9411"   # Zipkin receiver
      - "55679:55679" # zpages extension
    depends_on:
      - logtemplate
    networks:
      - logtemplate
  grafana:
    build: ../common/grafana
    depends_on:
      - "clickhouse"
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=vertamedia-clickhouse-datasource
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
    networks:
      - logtemplate
  clickhouse:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    volumes:
      - ./clickhouse:/var/lib/clickhouse
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - logtemplate
  logtemplate:
    build: ../common/logtemplate-image
    volumes:
      - ./logtemplate/application.conf:/logtemplate/LogTemplate/src/main/resources/application.conf
    depends_on:
      - "clickhouse"
    networks:
      - logtemplate
networks:
  logtemplate:
    driver: bridge