services:
  grafana:
    build: ./grafana
    container_name: grafana
    depends_on:
      - "clickhouse"
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=vertamedia-clickhouse-datasource
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards
    networks:
      - logtemplate
  clickhouse:
    container_name: clickhouse
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    volumes:
      - ./clickhouse:/var/lib/clickhouse
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - logtemplate
  logtemplate:
    container_name: logtemplate
    build: ./logtemplate-image
    depends_on:
      - "clickhouse"
    volumes:
      - ..:/logtemplate
    networks:
      - logtemplate
networks:
  logtemplate:
    driver: bridge